---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jordan/public_html/engevibings
    - /bin/git clone git@github.com:ItsJordanNL/enge-vibings $DEPLOYPATH || (cd $DEPLOYPATH && /bin/git pull origin main)
    - /bin/echo "Deployment completed."
